/* Plugin Template generated by Pawn Studio */
#include <functions>
#include <GNHook>

public Plugin:myinfo = 
{
	name = "GNHookManager",
	author = "GiayNhap",
	description = "<- Description ->",
	version = "1.0",
	url = "<- URL ->"
}

public OnPluginStart()
{
  RegConsoleCmd("gn_test", test); 
}

public Action:test(client, args)
{
//	setWeapon_event(1,"adasd" ,1, 1);
	test_method();
}
 //native void  setWeapon(String weapon,int ammo,int clip);
 
 
 public int Native_setWeapon(Handle plugin, int numParams)
{
	int len;
	int userid = GetNativeCell(1);
	GetNativeStringLength(2, len);

	if (len <= 0)
	{
		return 1;
	}

	char weapon [64];
	GetNativeString(2, weapon, 64);
	
	int ammo = GetNativeCell(3);
	int clip = GetNativeCell(4);
	setWeapon_event(userid,weapon,ammo,clip);
	return 0;
    
}
public int Native_updateTeamScore(Handle plugin, int numParams)
{
	int score = GetNativeCell(1);
	int ct = GetNativeCell(2);
	int ter = GetNativeCell(3);
	updateTeamScore_event(score,ct,ter);
}
public void setWeapon_event(int userid,char weapon[64] ,int ammo, int clip)
{
	Event event = CreateEvent("set_weapon",true);
 
	event.SetInt("userid", GetClientUserId(userid));
	event.SetString("weapon", weapon );
	event.SetInt("clip", ammo);
	event.SetInt("ammo", clip);
	event.Fire();
	PrintToConsoleAll("Call setWeapon")
	
}
public void updateTeamScore_event(int score,int ct,int ter)
{
	Event event = CreateEvent("set_team_score",true);
 
	event.SetInt("ctscore",ct);
	event.SetInt("terscore", ter);
	event.SetInt("totalscore", score);
	event.Fire();
	PrintToConsoleAll("Call updateTeamScore")
}

public void test_method()
{
	Event event = CreateEvent("test",true);
	event.Fire();
	PrintToConsoleAll("Call test")
}

public APLRes AskPluginLoad2(Handle myself, bool late, char[] error, int err_max)
{
   CreateNative("setWeapon", Native_setWeapon);
   CreateNative("updateTeamScore", Native_updateTeamScore);
   
   return APLRes_Success;
}